continue after retired VS Code extensions

diff --git a/run_after_install-vscode-extensions.sh.tmpl b/run_after_install-vscode-extensions.sh.tmpl
--- a/run_after_install-vscode-extensions.sh.tmpl
+++ b/run_after_install-vscode-extensions.sh.tmpl
@@ -8,7 +8,9 @@ fi
 
 while IFS= read -r extension; do
   case "$extension" in ''|'#'*) continue ;; esac
-  code --install-extension "$extension"
+  if ! code --install-extension "$extension"; then
+    printf '%s\n' "Unable to install VS Code extension: $extension" >&2
+  fi
 done <<'EXTENSIONS'
 {{ include ".chezmoitemplates/vscode-extensions.list" }}
 EXTENSIONS
